# Generated by Django 4.1.3 on 2022-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.BooleanField(),
        ),
    ]
