# Generated by Django 4.1.3 on 2022-12-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=500),
        ),
    ]
